### ISSUE TITLE
Consider using adaptive KSM settle detection algo from metrics test

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/ksm-throttler#23]
Over at https://github.com/clearcontainers/tests/blob/master/metrics/density/docker_memory_usage.sh#L126 we have a 'ksm settle algo' that watches `full_scans` and waits for the change in `pages_scanned` to settle down to an acceptably small change (currently using 5% as the cutoff trigger iirc).

We should consider if we want the throttler to have the same algo to decide when to scale back its aggresiveness.

**Comment by egernst** [comment]
We have limited utilization today of KSM, and this is quite stale.  Is it fair to close as will not fix?

**Comment by grahamwhaley** [comment]
OK with me. OK with you @jodh-intel ?
Feels like the ksm-throttler is going into retirement anyway....
