### ISSUE TITLE
install: path confict with cc package.

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/ksm-throttler#34]
Both kata and Clear Containers share the same service name.

We need to change the service name to avoid issues.

Install both kata an Clear Contaienrs without conficts

---

(replace this text with the output of the `kata-collect-data.sh` script, after
you have reviewed its content to ensure it does not contain any private
information).

**Comment by jodh-intel** [comment]
Fixed by 0ca55b4cf93c4e2622b5fa75f9adea9eea94d863 on #38.
