### ISSUE TITLE
Test the throttler in the CI

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/ksm-throttler#42]
For normal testing, we either don't install the throttler, or disable it. This ensures a repeatable CI, but means the throttler get neglected. In fact it's currently broken (until #38 lands).

We need to setup some sort of CI test that actively uses the throttler to ensure it dtrt.

**Comment by grahamwhaley** [comment]
Just please remember to make it work with https://github.com/kata-containers/tests/blob/master/.ci/run_metrics_PR_ci.sh#L68 if we end up modding the install/CI system - as the metrics need to be able to control if KSM is on/off ;-)

**Comment by jodh-intel** [comment]
/me thinks the throttler must feel rather unloved :broken_heart: :smile:
